#!/usr/bin/env bash
# This Bash script displays 'To infinity and beyond' indefinitely.
# In between each iteration of the loop, sleep 2 is added

# Using the SIGUSR1 kill signal
trap SIGUSR1

while true
do
	echo "To infinity and beyond"
	sleep 2
done


