#!/usr/bin/env bash
# This Bash script displays 'To infinity and beyond' indefinitely.
# In between each iteration of the loop, sleep 2 is added

# Save PID to a file
echo $$ > /tmp/4_to_infinity_pid 

while true
do
	echo "To infinity and beyond"
	sleep 2
done


