#!/usr/bin/env bash

# This Bash script displays:

# 'To infinity and beyond' indefinitely
# With a sleep 2 in between each iteration
# 'I am invincible!!!' when receiving a SIGKILL signal

# Store PID for easier targeting
echo $$ > /tmp/7_highlander_pid

# Prints message on SIGKILL
trap SIGKILL

for (( ; ; ))
do
	echo "To infinity and beyond"
	sleep 2
done
