#!/usr/bin/env bash

# This Bash script kills the process 7-highlander upon invoking SIGKILL

# Read PID from file
if [[ -f /tmp/7_highlander_pid ]]
then
	pid=$(cat /tmp/7_highlander_pid )
	if [[ -n "$pid" ]]
	then
		kill -SIGKILL "$pid"
	fi
fi
