#!/usr/bin/env bash
# Print 'Best School' and the 'Hi' in the 
# 9th iteration

i=1

while [[ $i -le 10 ]]
do
	if [[ $i -eq 9 ]]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

	i=$(( i + 1 ))
done
